import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { DynamicEntityServiceProxy, CreateDynamicEntityTypeDto, UpdateDynamicEntityTypeDto, DynamicEntityTypeDto } from '@app/core/services/service-proxies';

@Component({
    selector: 'app-dynamic-entity-type-widget',
    templateUrl: './dynamic-entity-type-widget.component.html',
    styleUrls: ['./dynamic-entity-type-widget.component.scss'],
    standalone: true,
    imports: [CommonModule, FormsModule],
    providers: [DynamicEntityServiceProxy]
})
export class DynamicEntityTypeWidgetComponent {
    @Input() entityType: DynamicEntityTypeDto | null = null;
    @Output() close = new EventEmitter<boolean>();
    @Output() saved = new EventEmitter<void>();

    name = '';
    key = '';
    description = '';
    isActive = true;
    fieldsJson: any[] = [];
    loading = false;
    error = '';

    ngOnInit() {
        if (this.entityType) {
            this.name = this.entityType.name;
            this.key = this.entityType.key;
            this.description = this.entityType.description;
            this.isActive = this.entityType.isActive;
            this.fieldsJson = this.entityType.fieldsJson ? JSON.parse(this.entityType.fieldsJson) : [];
            this.fieldsJson = this.fieldsJson.filter((field) => !field?.autoGeneratedDatePart);
            this.normalizeFileFieldConfigs();
            this.normalizeDateFieldConfigs();
        }
    }

    /**
     * Auto-generate key from name when name changes
     */
    onNameChange(): void {
        // Only auto-generate key if it's a new entity or key is empty
        if (!this.entityType || !this.key) {
            this.key = this.convertToKey(this.name);
        }
    }

    /**
     * Validate and format field name when it changes
     */
    onFieldNameBlur(field: any): void {
        if (field.name) {
            // Convert to camelCase for consistency
            field.name = this.convertToCamelCase(field.name);
            
            // Auto-generate label if empty
            if (!field.label) {
                field.label = this.formatFieldLabel(field.name);
            }
        }
    }

    /**
     * Auto-generate field name from label when label changes
     */
    onFieldLabelChange(field: any): void {
        if (field.label) {
            field.name = this.convertToCamelCase(field.label);
        }
    }

    onFieldsChanged(fields: any[]) {
        this.fieldsJson = fields;
    }

    onFieldTypeChange(field: any): void {
        if (field.type === 'file') {
            field.fileMode = field.fileMode === 'multiple' ? 'multiple' : 'single';
            field.maxFiles = field.fileMode === 'multiple' ? Math.max(1, Number(field.maxFiles ?? 5)) : 1;
            field.maxSizeMB = Math.max(1, Number(field.maxSizeMB ?? 10));

            const accepted = field.acceptedTypes;
            if (Array.isArray(accepted)) {
                field.acceptedTypes = accepted.join(', ');
            } else if (!accepted || typeof accepted !== 'string') {
                field.acceptedTypes = '.pdf, .jpg, .jpeg, .png, .doc, .docx';
            }
        }

        if (field.type === 'date') {
            field.splitDateParts = !!field.splitDateParts;
            field.datePartVisibility = this.normalizeDatePartVisibility(field.datePartVisibility);
            field.datePartKeys = {
                day: `${field.name || 'date'}_day`,
                month: `${field.name || 'date'}_month`,
                year: `${field.name || 'date'}_year`
            };
        }

        if (field.type === 'idNumber') {
            const baseName = field.name || '';
            const targetAgeName = baseName ? `${baseName}_age` : 'age';
            const targetGenderName = baseName ? `${baseName}_gender` : 'gender';
            const targetDateOfBirthName = baseName ? `${baseName}_dateOfBirth` : 'dateOfBirth';

            const normalizedNames = new Set(
                this.fieldsJson
                    .map((f) => (f?.name || '').toString().trim().toLowerCase())
                    .filter((name) => !!name)
            );

            const hasAge = normalizedNames.has(targetAgeName.toLowerCase()) || normalizedNames.has('age');
            const hasGender = normalizedNames.has(targetGenderName.toLowerCase()) || normalizedNames.has('gender');
            const hasDateOfBirth =
                normalizedNames.has(targetDateOfBirthName.toLowerCase()) ||
                normalizedNames.has('dateofbirth') ||
                normalizedNames.has('dob');

            let inserted = false;
            let insertIdx = this.fieldsJson.indexOf(field) + 1;

            if (!hasDateOfBirth) {
                this.fieldsJson.splice(insertIdx, 0, {
                    name: targetDateOfBirthName,
                    label: 'Date of Birth',
                    type: 'date',
                    required: false,
                    placeholder: 'Auto-populated from ID number',
                    options: '',
                    order: 0,
                    showInList: true,
                    filterable: true
                });
                insertIdx++;
                inserted = true;
            }

            if (!hasAge) {
                this.fieldsJson.splice(insertIdx, 0, {
                    name: targetAgeName,
                    label: 'Age',
                    type: 'number',
                    required: false,
                    placeholder: 'Auto-calculated',
                    options: '',
                    order: 0,
                    showInList: true,
                    filterable: true
                });
                insertIdx++;
                inserted = true;
            }

            if (!hasGender) {
                this.fieldsJson.splice(insertIdx, 0, {
                    name: targetGenderName,
                    label: 'Gender',
                    type: 'select',
                    required: false,
                    placeholder: 'Select gender',
                    options: 'Male, Female',
                    order: 0,
                    showInList: true,
                    filterable: true
                });
                insertIdx++;
                inserted = true;
            }

            if (inserted) {
                this.fieldsJson.forEach((f, i) => (f.order = i + 1));
            }
        }
    }

    addField() {
        const index = this.fieldsJson.length + 1;
        this.fieldsJson.push({
            name: '', // Start empty, user will fill in or it will auto-generate from label
            label: `New Field ${index}`,
            type: 'text',
            required: false,
            placeholder: '',
            options: '',
            fileMode: 'single',
            maxFiles: 1,
            maxSizeMB: 10,
            acceptedTypes: '.pdf, .jpg, .jpeg, .png, .doc, .docx',
            order: index,
            showInList: true,
            filterable: true
        });
    }

    onFileModeChange(field: any): void {
        if (field.type !== 'file') {
            return;
        }

        if (field.fileMode === 'multiple') {
            field.maxFiles = Math.max(1, Number(field.maxFiles ?? 5));
        } else {
            field.maxFiles = 1;
        }
    }

    onDateSplitToggle(field: any): void {
        field.splitDateParts = !!field.splitDateParts;
        field.datePartVisibility = this.normalizeDatePartVisibility(field.datePartVisibility);
        field.datePartKeys = this.buildDatePartKeys(field.name);
    }

    onDatePartVisibilityChange(field: any): void {
        field.datePartVisibility = this.normalizeDatePartVisibility(field.datePartVisibility);
    }

    removeField(idx: number) {
        this.fieldsJson.splice(idx, 1);
    }

    save() {
        // Validate and format names before saving
        if (!this.name || !this.key) {
            this.error = 'Name and Key are required.';
            return;
        }

        // Ensure key is in proper format
        this.key = this.convertToKey(this.key);

        // Validate all fields have names
        const invalidFields = this.fieldsJson.filter(f => !f.name || !f.label);
        if (invalidFields.length > 0) {
            this.error = 'All fields must have a name and label.';
            return;
        }

        const preparedFields = this.prepareFieldsForSave();

        // Format all field names to camelCase
        preparedFields.forEach(field => {
            if (!field.autoGeneratedDatePart) {
                field.name = this.convertToCamelCase(field.name);
            }

            if (field.type === 'file') {
                field.fileMode = field.fileMode === 'multiple' ? 'multiple' : 'single';
                field.maxFiles = field.fileMode === 'multiple' ? Math.max(1, Number(field.maxFiles ?? 5)) : 1;
                field.maxSizeMB = Math.max(1, Number(field.maxSizeMB ?? 10));
                field.acceptedTypes = (field.acceptedTypes || '')
                    .split(',')
                    .map((o: string) => o.trim())
                    .filter((o: string) => !!o);

                field.fileConfig = {
                    allowMultiple: field.fileMode === 'multiple',
                    maxFiles: field.maxFiles,
                    maxSizeMB: field.maxSizeMB,
                    acceptedTypes: field.acceptedTypes
                };
            }
        });

        this.loading = true;
        this.error = '';
        const dto = this.entityType
            ? ({
                  id: this.entityType.id,
                  name: this.name,
                  key: this.key,
                  description: this.description,
                  isActive: this.isActive,
                                    fieldsJson: JSON.stringify(preparedFields)
              } as UpdateDynamicEntityTypeDto)
            : ({
                  name: this.name,
                  key: this.key,
                  description: this.description,
                  isActive: this.isActive,
                                    fieldsJson: JSON.stringify(preparedFields)
              } as CreateDynamicEntityTypeDto);
        let call;
        if (this.entityType) {
            const updateDto = dto as UpdateDynamicEntityTypeDto;
            call = this.entityTypeService.entityType_Update(updateDto);
        } else {
            const createDto = dto as CreateDynamicEntityTypeDto;
            call = this.entityTypeService.entityType_Create(createDto);
        }
        call.subscribe({
            next: () => {
                this.loading = false;
                this.saved.emit();
                this.close.emit(true);
            },
            error: () => {
                this.error = 'Failed to save entity type.';
                this.loading = false;
            }
        });
    }

    cancel() {
        this.close.emit(false);
    }

    constructor(private entityTypeService: DynamicEntityServiceProxy) {}

    /**
     * Format a string to be user-friendly with proper spacing and title case
     * Examples: "Extended_Family_Members" -> "Extended Family Members"
     *           "beneficiaries" -> "Beneficiaries"
     */
    formatToUserFriendly(value: string): string {
        if (!value) return '';
        return value
            .split('_')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join(' ');
    }

    /**
     * Convert user-friendly name to a proper key format
     * Examples: "Extended Family Members" -> "Extended_Family_Members"
     *           "My Custom Type" -> "My_Custom_Type"
     */
    convertToKey(value: string): string {
        if (!value) return '';
        // Remove special characters except spaces and underscores
        return value
            .trim()
            .replace(/[^a-zA-Z0-9\s_]/g, '')
            .split(/\s+/)
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('_');
    }

    /**
     * Convert field name to camelCase format
     * Examples: "Full Name" -> "fullName", "Date of Birth" -> "dateOfBirth"
     */
    convertToCamelCase(value: string): string {
        if (!value) return '';
        const words = value
            .trim()
            .replace(/[^a-zA-Z0-9\s]/g, '')
            .split(/\s+/);
        
        if (words.length === 0) return '';
        
        return words[0].toLowerCase() + words.slice(1)
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('');
    }

    /**
     * Format field label from camelCase/PascalCase
     * Examples: "fullName" -> "Full Name", "dateOfBirth" -> "Date Of Birth"
     */
    formatFieldLabel(fieldName: string): string {
        if (!fieldName) return '';
        return fieldName
            .replace(/([A-Z])/g, ' $1')
            .replace(/^./, str => str.toUpperCase())
            .trim();
    }

    private normalizeFileFieldConfigs(): void {
        this.fieldsJson.forEach((field) => {
            if (field.type !== 'file') {
                return;
            }

            field.fileMode = field.fileMode === 'multiple' || !!field.fileConfig?.allowMultiple ? 'multiple' : 'single';
            field.maxFiles = typeof field.maxFiles === 'number'
                ? field.maxFiles
                : typeof field.fileConfig?.maxFiles === 'number'
                  ? field.fileConfig.maxFiles
                  : field.fileMode === 'multiple'
                    ? 5
                    : 1;
            field.maxSizeMB = typeof field.maxSizeMB === 'number'
                ? field.maxSizeMB
                : typeof field.fileConfig?.maxSizeMB === 'number'
                  ? field.fileConfig.maxSizeMB
                  : 10;

            const accepted = field.acceptedTypes ?? field.fileConfig?.acceptedTypes;
            field.acceptedTypes = Array.isArray(accepted)
                ? accepted.join(', ')
                : typeof accepted === 'string'
                  ? accepted
                  : '.pdf, .jpg, .jpeg, .png, .doc, .docx';
        });
    }

    private normalizeDateFieldConfigs(): void {
        this.fieldsJson.forEach((field) => {
            if (field.type !== 'date') {
                return;
            }

            field.splitDateParts = !!field.splitDateParts;
            field.datePartVisibility = this.normalizeDatePartVisibility(field.datePartVisibility);
            field.datePartKeys = this.buildDatePartKeys(field.name, field.datePartKeys);
        });
    }

    private normalizeDatePartVisibility(value: any): { day: boolean; month: boolean; year: boolean } {
        return {
            day: value?.day !== false,
            month: value?.month !== false,
            year: value?.year !== false
        };
    }

    private buildDatePartKeys(fieldName: string, existing?: any): { day: string; month: string; year: string } {
        const normalizedBase = this.convertToCamelCase(fieldName || 'date') || 'date';
        return {
            day: existing?.day || `${normalizedBase}_day`,
            month: existing?.month || `${normalizedBase}_month`,
            year: existing?.year || `${normalizedBase}_year`
        };
    }

    private prepareFieldsForSave(): any[] {
        const baseFields = this.fieldsJson
            .map((field) => {
                const clone = { ...field };
                clone.name = this.convertToCamelCase(clone.name);

                if (clone.type === 'date') {
                    clone.splitDateParts = !!clone.splitDateParts;
                    clone.datePartVisibility = this.normalizeDatePartVisibility(clone.datePartVisibility);
                    clone.datePartKeys = this.buildDatePartKeys(clone.name, clone.datePartKeys);
                }

                return clone;
            })
            .filter((field) => !field?.autoGeneratedDatePart);

        const expanded: any[] = [];

        for (const field of baseFields) {
            expanded.push(field);

            if (field.type !== 'date' || !field.splitDateParts) {
                continue;
            }

            const visibility = this.normalizeDatePartVisibility(field.datePartVisibility);
            const keys = this.buildDatePartKeys(field.name, field.datePartKeys);
            field.datePartKeys = keys;

            expanded.push(
                {
                    name: keys.day,
                    label: `${field.label} Day`,
                    type: 'number',
                    required: false,
                    placeholder: 'Auto-derived day',
                    options: '',
                    order: 0,
                    showInList: false,
                    filterable: false,
                    hidden: !visibility.day,
                    readOnly: true,
                    autoGeneratedDatePart: true,
                    parentDateFieldKey: field.name,
                    datePart: 'day'
                },
                {
                    name: keys.month,
                    label: `${field.label} Month`,
                    type: 'number',
                    required: false,
                    placeholder: 'Auto-derived month',
                    options: '',
                    order: 0,
                    showInList: false,
                    filterable: false,
                    hidden: !visibility.month,
                    readOnly: true,
                    autoGeneratedDatePart: true,
                    parentDateFieldKey: field.name,
                    datePart: 'month'
                },
                {
                    name: keys.year,
                    label: `${field.label} Year`,
                    type: 'number',
                    required: false,
                    placeholder: 'Auto-derived year',
                    options: '',
                    order: 0,
                    showInList: false,
                    filterable: false,
                    hidden: !visibility.year,
                    readOnly: true,
                    autoGeneratedDatePart: true,
                    parentDateFieldKey: field.name,
                    datePart: 'year'
                }
            );
        }

        expanded.forEach((f, index) => {
            f.order = index + 1;
        });

        return expanded;
    }
}
