import { defineConfig } from 'orval';

export default defineConfig({
  funeralApi: {
    input: {
      target: 'http://localhost:3000/api-docs/swagger.json',
    },
    output: {
      mode: 'tags-split',
      target: './src/app/core/services/generated',
      schemas: './src/app/core/models',
      client: 'angular',
      mock: false,
      baseUrl: 'http://localhost:3000',
      override: {
        header: (info) => [
          `/**`,
          ` * Generated by orval v${info.version} 🍺`,
          ` * Do not edit manually.`,
          ` * ${info.title}`,
          ` * ${info.description}`,
          ` */`,
        ],
      },
    },
  },
});
