/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface AssetStatsDto {
  totalAssets: string;
  availableAssets: string;
  checkedOutAssets: string;
  underMaintenanceAssets: string;
  retiredAssets: string;
  overdueCheckouts: string;
}
