/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export type AssetStatus = typeof AssetStatus[keyof typeof AssetStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AssetStatus = {
  Available: 0,
  CheckedOut: 1,
  UnderMaintenance: 2,
  OutOfService: 3,
  Retired: 4,
} as const;
