/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { CalculatePremiumRequestDtoDependentsItem } from './calculatePremiumRequestDtoDependentsItem';
import type { CalculatePremiumRequestDtoBeneficiariesItem } from './calculatePremiumRequestDtoBeneficiariesItem';

export interface CalculatePremiumRequestDto {
  coverAmount: number;
  dependents: CalculatePremiumRequestDtoDependentsItem[];
  beneficiaries: CalculatePremiumRequestDtoBeneficiariesItem[];
}
