/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export type CheckoutStatus = typeof CheckoutStatus[keyof typeof CheckoutStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CheckoutStatus = {
  Active: 0,
  Returned: 1,
  Overdue: 2,
  Cancelled: 3,
} as const;
