/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface CheckIdNumberResponseDto {
  Exists: boolean;
  IsMainMember: boolean;
  HasUserAccount: boolean;
  MemberId: string;
  MemberName: string;
  ContactEmail: string;
  ContactPhone: string;
  Message: string;
}
