/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface CreateMemberDto {
  id: string;
  name: string;
  address: string;
  title: string;
  firstNames: string;
  surname: string;
  dateOfBirth: string;
  email: string;
  phone1: string;
  phone2: string;
  identificationNumber: string;
  sourceOfIncome: number;
  sourceOfIncomeOther: string;
  streetAddress: string;
  city: string;
  province: number;
  postalCode: string;
  isReplacingExistingPolicy: boolean;
  existingPolicyNumber: string;
  existingInsurerName: string;
  existingPolicyPaidUpToDate: boolean;
  existingPolicyWaitingPeriodExpired: boolean;
  sameBenefitAsExistingPolicy: boolean;
  benefitDifferenceNotes: string;
  occupation: string;
  workPhoneNumber: string;
  passportNumber: string;
  countryOfBirth: string;
  countryOfResidence: string;
  citizenship: string;
  nationality: string;
  isForeigner: boolean;
  workPermitNumber: string;
  policyId: string;
}
