/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export type DependentType = typeof DependentType[keyof typeof DependentType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DependentType = {
  Spouse: 1,
  Child: 2,
  ExtendedFamily: 3,
  Parent: 4,
  Other: 5,
} as const;
