/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface DependentOtpRecord {
  Id: string;
  MainMemberId: string;
  IdNumber: string;
  OtpCode: string;
  ContactMethod: string;
  ContactValue: string;
  CreatedAt: string;
  ExpiresAt: string;
  IsUsed: boolean;
}
