/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { DocumentComplianceStatusMissingDocumentsItem } from './documentComplianceStatusMissingDocumentsItem';
import type { DocumentComplianceStatusPendingVerificationItem } from './documentComplianceStatusPendingVerificationItem';
import type { DocumentComplianceStatusRejectedDocumentsItem } from './documentComplianceStatusRejectedDocumentsItem';

export interface DocumentComplianceStatus {
  isCompliant: boolean;
  totalRequired: number;
  totalUploaded: number;
  totalApproved: number;
  missingDocuments: DocumentComplianceStatusMissingDocumentsItem[];
  pendingVerification: DocumentComplianceStatusPendingVerificationItem[];
  rejectedDocuments: DocumentComplianceStatusRejectedDocumentsItem[];
}
