/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { GetApiLandingPageLandingPageGetLandingPage200LayoutsItem } from './getApiLandingPageLandingPageGetLandingPage200LayoutsItem';

export type GetApiLandingPageLandingPageGetLandingPage200 = {
  layouts?: GetApiLandingPageLandingPageGetLandingPage200LayoutsItem[];
};
