/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

/**
 * @nullable
 */
export type GetApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItemContent = { [key: string]: unknown } | null;
