/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { GetApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItemContent } from './getApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItemContent';

export type GetApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItem = {
  id?: number;
  sortOrder?: number;
  componentType?: string;
  /** @nullable */
  content?: GetApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItemContent;
};
