/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { GetApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItem } from './getApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItem';

export type GetApiLandingPageLandingPageGetLandingPage200LayoutsItem = {
  id?: number;
  sortOrder?: number;
  sectionType?: string;
  components?: GetApiLandingPageLandingPageGetLandingPage200LayoutsItemComponentsItem[];
};
