/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface MemberBankingDetailDto {
  id: string;
  memberId: string;
  bankName: string;
  accountNumber: string;
  accountType: string;
  branchCode: string;
  branchName: string;
  accountHolderName: string;
  debitDay: number;
  paymentMethod: number;
  isVerified: boolean;
  createdAt: string;
}
