/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { MemberDocumentStatusDtoDocumentsItem } from './memberDocumentStatusDtoDocumentsItem';

export interface MemberDocumentStatusDto {
  memberId: string;
  totalRequired: number;
  totalUploaded: number;
  documents: MemberDocumentStatusDtoDocumentsItem[];
}
