/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { MemberOnboardingDataDtoData } from './memberOnboardingDataDtoData';

export interface MemberOnboardingDataDto {
  memberId: string;
  data: MemberOnboardingDataDtoData;
}
