/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface MemberProfileCompletionDto {
  id: string;
  memberId: string;
  hasDependents: boolean;
  hasBeneficiaries: boolean;
  hasUploadedIdDocument: boolean;
  hasAcceptedTerms: boolean;
  hasCompletedCustomForms: boolean;
  hasUploadedRequiredDocuments: boolean;
  isProfileComplete: boolean;
  profileCompletedAt: string;
  completionPercentage: number;
  nextStepRecommendation: string;
}
