/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export type MemberStatus = typeof MemberStatus[keyof typeof MemberStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MemberStatus = {
  PendingApproval: 0,
  Active: 1,
  Suspended: 2,
  Inactive: 3,
  Rejected: 4,
} as const;
