/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface MemberDto {
  id: string;
  tenantId: string;
  name: string;
  address: string;
  title: string;
  firstNames: string;
  surname: string;
  dateOfBirth: string;
  email: string;
  phone1: string;
  phone2: string;
  identificationNumber: string;
  sourceOfIncome: string;
  sourceOfIncomeOther: string;
  streetAddress: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
  isReplacingExistingPolicy: boolean;
  existingPolicyNumber: string;
  existingInsurerName: string;
  existingPolicyPaidUpToDate: boolean;
  existingPolicyWaitingPeriodExpired: boolean;
  sameBenefitAsExistingPolicy: boolean;
  benefitDifferenceNotes: string;
  occupation: string;
  workPhoneNumber: string;
  passportNumber: string;
  countryOfBirth: string;
  countryOfResidence: string;
  citizenship: string;
  nationality: string;
  isForeigner: boolean;
  workPermitNumber: string;
  status: string;
  paymentStatus: string;
  nextPaymentDate: string;
  isIdVerified: boolean;
  idVerifiedAt: string;
  isLifeVerified: boolean;
  lifeVerifiedAt: string;
  signatureDataUrl: string;
  signedAt: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}
