/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export type PostApiClaimClaimUpdateClaimDocumentsIdBody = { [key: string]: unknown };
