/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export type PostApiFileUploadFileUploadFileBody = {
  file?: Blob;
  entityType?: string;
  entityId?: string;
  documentType?: string;
  memberDocumentType?: number;
  isRequired?: boolean;
};
