/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { PremiumCalculationResultDtoBreakdownItem } from './premiumCalculationResultDtoBreakdownItem';

export interface PremiumCalculationResultDto {
  basePremium: number;
  extendedFamilyPremium: number;
  totalMonthlyPremium: number;
  breakdown: PremiumCalculationResultDtoBreakdownItem[];
  message: string;
}
