/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */
import type { ProfileCompletionStatusDtoCompletedStepsItem } from './profileCompletionStatusDtoCompletedStepsItem';
import type { ProfileCompletionStatusDtoRemainingStepsItem } from './profileCompletionStatusDtoRemainingStepsItem';
import type { ProfileCompletionStatusDtoProfileCompletion } from './profileCompletionStatusDtoProfileCompletion';

export interface ProfileCompletionStatusDto {
  isComplete: boolean;
  completionPercentage: number;
  completedSteps: ProfileCompletionStatusDtoCompletedStepsItem[];
  remainingSteps: ProfileCompletionStatusDtoRemainingStepsItem[];
  nextStepRecommendation: string;
  profileCompletion: ProfileCompletionStatusDtoProfileCompletion;
  dependentsCount: number;
  beneficiariesCount: number;
  uploadedDocumentsCount: number;
  requiredDocumentsCount: number;
  hasAcceptedLatestTerms: boolean;
}
