/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface SubscriptionPlanDto {
  id: string;
  name: string;
  description: string;
  monthlyPrice: number;
  allowedTenantType: string;
  features: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updatedBy: string;
}
