/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface TenantSettingDto {
  id: string;
  settings: string;
  ozowApiKey: string;
  ozowSiteCode: string;
  ozowPrivateKey: string;
  logo: string;
  favicon: string;
  tenantName: string;
  tenantDomain: string;
}
