/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface TermsAcceptanceDto {
  id: string;
  memberId: string;
  termsAndConditionsId: string;
  tenantId: string;
  acceptedAt: string;
  ipAddress: string;
  userAgent: string;
  acceptedVersion: string;
}
