/**
 * /**
 *  * Generated by orval v1.0.0 🍺
 *  * Do not edit manually.
 *  * Funeral API
 *  * API for managing funeral services, members, policies, claims, and more.
 *  *\/
 */

export interface UpdateOnboardingFieldConfigurationDto {
  id: string;
  fieldName: string;
  displayLabel: string;
  fieldType: string;
  category: string;
  displayOrder: number;
  isRequired: boolean;
  isEnabled: boolean;
  placeholder: string;
  helpText: string;
  validationRules: string;
  options: string;
  defaultValue: string;
}
